#!/usr/bin/env bash
# Vendoring sync: push the canonical egress files into each devcontainer's
# .devcontainer/, and GENERATE each project's baked allowlist from the shared
# base + that project's overlay.
#
# Edit init-firewall.sh / squid.conf / base-allowlist.txt / launcher-common.sh
# HERE, or a project's .devcontainer/allowlist.extra.txt, then run this and
# rebuild the affected containers. The generated .devcontainer/allowlist.txt is
# NOT hand-edited.
#
# Targets come from paths.sh (shared with audit.sh) — see that file for why.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"
BASE="$HERE/base-allowlist.txt"

# Modes:
#   (default)        copy + generate, then VERIFY each copy with cmp; a missing
#                    target is a HARD failure (this is the bug paths.sh exists to
#                    prevent — a renamed/moved project silently dropping out of
#                    the egress lock). Pass --allow-missing to downgrade to a warn.
#   --check          verify-only: compare every vendored copy + generated allowlist
#                    against what sync WOULD write, and exit non-zero on any drift
#                    (a hand-edited vendored init-firewall.sh/squid.conf/allowlist,
#                    or a missing target). Writes nothing. Good as a pre-commit gate.
MODE=sync
ALLOW_MISSING=0
for arg in "$@"; do
  case "$arg" in
    --check)         MODE=check ;;
    --allow-missing) ALLOW_MISSING=1 ;;
    -h|--help)       echo "usage: sync.sh [--check] [--allow-missing]"; exit 0 ;;
    *) echo "sync: unknown arg '$arg' (use --check, --allow-missing)" >&2; exit 2 ;;
  esac
done

[[ -f "$BASE" ]] || { echo "sync: missing base-allowlist.txt at $BASE" >&2; exit 1; }
# shellcheck source=paths.sh
source "$HERE/paths.sh"

# Effective (non-comment, non-blank) host set of a file — used by the fail-closed
# host-count safety check in gen_allowlist and by the "N hosts" sync message.
domains() { grep -vE '^\s*#' "$1" 2>/dev/null | grep -vE '^\s*$' | sort -u; }

# Minimum sane host count for a generated allowlist. The shared base alone always
# contributes several hosts, so a generated file at/below this floor means the base
# was accidentally emptied or corrupted — which fails every container closed but
# SILENTLY. Refuse to write such a file.
ALLOWLIST_MIN_HOSTS=1

# Print an allowlist.extra.txt, dropping host lines already present in the base host
# set ($2, newline-separated); comments and blank lines are kept verbatim. A host in
# both files would otherwise appear twice in the baked allowlist — harmless to squid,
# but it inflates the host count and misleads a human auditor. bash-3.2 safe.
_emit_extras_deduped() {
  local extra="$1" base_hosts="$2" line host
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^[[:space:]]*# || -z "${line//[[:space:]]/}" ]]; then
      printf '%s\n' "$line"; continue
    fi
    host="${line//[[:space:]]/}"
    printf '%s\n' "$base_hosts" | grep -qxF -- "$host" && continue  # in base → drop dup
    printf '%s\n' "$line"
  done < "$extra"
}

gen_allowlist() {
  local dst="$1" project="$2"
  local extra="$dst/allowlist.extra.txt" out="${3:-$dst/allowlist.txt}"
  local base_hosts outdir tmp n
  base_hosts="$(domains "$BASE")"
  outdir="$(dirname "$out")"
  # Write to a temp in the SAME dir, then atomically mv into place, so an interrupt
  # or disk-full never leaves a truncated allowlist.txt (egress-safe but silently
  # broken until re-sync, with no signal).
  tmp="$(mktemp "$outdir/.allowlist.XXXXXX")" || { echo "sync: ERROR mktemp failed in $outdir" >&2; exit 1; }
  {
    echo "# GENERATED by LockBox/sync.sh — DO NOT EDIT THIS FILE."
    echo "# Effective allowlist = base-allowlist.txt + ${project}/allowlist.extra.txt"
    echo "# Edit the base (LockBox/base-allowlist.txt) or this project's"
    echo "# allowlist.extra.txt, then re-run ./sync.sh and rebuild the container."
    echo
    echo "# ==== shared base ===="
    cat "$BASE"
    echo
    if [[ -f "$extra" ]]; then
      echo "# ==== ${project} project-specific extras ===="
      _emit_extras_deduped "$extra" "$base_hosts"
    else
      echo "# (no ${project}/allowlist.extra.txt — base only)"
    fi
  } > "$tmp"
  # Fail-closed: never install an allowlist that lost its hosts (e.g. an emptied base).
  n="$(domains "$tmp" | wc -l | tr -d ' ')"
  if (( n < ALLOWLIST_MIN_HOSTS )); then
    rm -f "$tmp"
    echo "sync: ERROR generated allowlist for '${project}' has ${n} host(s) (< ${ALLOWLIST_MIN_HOSTS}); refusing to write. Is base-allowlist.txt empty?" >&2
    exit 1
  fi
  # mktemp makes the temp 0600; the baked /etc/squid/allowlist.txt is read by squid
  # running as the non-root `proxy` user, so it must be world-readable. Normalize to
  # 0644 (a data file needs no +x either — the old 0755 was spurious).
  chmod 0644 "$tmp"
  mv "$tmp" "$out"
}

# Files vendored verbatim (canonical name -> per-project name; same here). Read from
# the shared manifest so a fourth canonical file is added in ONE place — CI's
# vendored job reads the same vendored-files.txt.
VENDORED=()
while IFS= read -r _vf || [[ -n "$_vf" ]]; do
  if [[ "$_vf" =~ ^[[:space:]]*# ]] || [[ -z "${_vf//[[:space:]]/}" ]]; then continue; fi
  VENDORED+=("$_vf")
done < "$HERE/vendored-files.txt"
(( ${#VENDORED[@]} > 0 )) || { echo "sync: ERROR no vendored files listed in $HERE/vendored-files.txt" >&2; exit 1; }

synced=0 skipped=0 drift=0 checked=0
for dst in "${EGRESS_DEVCONTAINERS[@]}"; do
  if [[ ! -d "$dst" ]]; then
    echo "SKIP (missing) -> $dst" >&2
    skipped=$((skipped + 1))
    continue
  fi
  project="$(basename "$(dirname "$dst")")"

  if [[ "$MODE" == check ]]; then
    # Verify-only: every vendored copy + the generated allowlist must already
    # match what sync WOULD write; any difference is drift (hand-edit / stale).
    for f in "${VENDORED[@]}"; do
      [[ -f "$HERE/$f" ]] || continue
      if ! cmp -s "$HERE/$f" "$dst/$f"; then
        echo "DRIFT: $dst/$f differs from canonical $f" >&2; drift=$((drift + 1))
      fi
    done
    tmp="$(mktemp)"; gen_allowlist "$dst" "$project" "$tmp"
    if ! cmp -s "$tmp" "$dst/allowlist.txt"; then
      echo "DRIFT: $dst/allowlist.txt is stale (re-run ./sync.sh)" >&2; drift=$((drift + 1))
    fi
    rm -f "$tmp"
    checked=$((checked + 1))
    continue
  fi

  # Sync: copy, then VERIFY each copy landed byte-identical (a silently failed cp
  # would otherwise leave a stale/partial egress file in place).
  for f in "${VENDORED[@]}"; do
    [[ -f "$HERE/$f" ]] || continue
    cp "$HERE/$f" "$dst/$f"
    cmp -s "$HERE/$f" "$dst/$f" || { echo "sync: ERROR copy verify failed for $dst/$f" >&2; exit 1; }
  done
  # Guard the chmod on the copy having landed: if canonical init-firewall.sh is
  # absent the cp above is skipped, and an unconditional chmod on a nonexistent file
  # would abort with a confusing error instead of the clear per-file message.
  if [[ -f "$dst/init-firewall.sh" ]]; then chmod +x "$dst/init-firewall.sh"; fi
  gen_allowlist "$dst" "$project"
  echo "synced + generated allowlist ($(domains "$dst/allowlist.txt" | wc -l | tr -d ' ') hosts) -> $dst"
  synced=$((synced + 1))
done

if [[ "$MODE" == check ]]; then
  if (( drift == 0 && skipped == 0 )); then
    echo "✓ check: all $checked vendored copies + allowlists are in sync."
    exit 0
  fi
  echo "✗ check: $drift drift, $skipped missing target(s). Run ./sync.sh." >&2
  exit 1
fi

echo "Done: $synced synced, $skipped skipped. Rebuild affected containers so the baked copies update."
# A missing target means a managed container silently stopped receiving the
# egress lock — fail loudly unless explicitly allowed.
if (( skipped > 0 )) && (( ! ALLOW_MISSING )); then
  echo "sync: ERROR — $skipped target(s) missing (see SKIP above). Fix paths.sh or pass --allow-missing." >&2
  exit 1
fi
