#!/usr/bin/env bash
# Vendoring sync: push the canonical egress files into each devcontainer's
# .devcontainer/, and GENERATE each project's baked allowlist from the shared
# base + that project's overlay.
#
# Edit init-firewall.sh / squid.conf / base-allowlist.txt / launcher-common.sh
# HERE, or a project's .devcontainer/allowlist.extra.txt, then run this and
# rebuild the affected containers. The generated .devcontainer/allowlist.txt is
# NOT hand-edited.
#
# Targets come from paths.sh (shared with audit.sh) — see that file for why.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"
BASE="$HERE/base-allowlist.txt"
VERSION_FILE="$HERE/VERSION"

# Single-source version, stamped into every vendored copy for provenance.
[[ -f "$VERSION_FILE" ]] || { echo "sync: missing VERSION at $VERSION_FILE" >&2; exit 1; }
LOCKBOX_VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
[[ -n "$LOCKBOX_VERSION" ]] || { echo "sync: VERSION file is empty" >&2; exit 1; }

# Portable SHA-256 of a file's content (Linux CI has sha256sum; macOS host has shasum).
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# Each vendored copy is the canonical content PLUS a deterministic provenance stamp
# (LockBox version + the canonical file's SHA-256; see gen_vendored), so the drift
# check regenerates-and-compares rather than expecting byte-identical files.
#
# Modes:
#   (default)        generate (canonical+stamp, and each allowlist), then VERIFY each
#                    write by regenerating and cmp'ing; a missing target is a HARD
#                    failure (this is the bug paths.sh exists to prevent — a
#                    renamed/moved project silently dropping out of the egress lock).
#                    Pass --allow-missing to downgrade to a warn.
#   --check          verify-only: regenerate every vendored copy + allowlist and
#                    compare against what is committed, exiting non-zero on any drift
#                    (a hand-edited vendored file, a stale stamp, or a missing target).
#                    Writes nothing. Good as a pre-commit gate.
MODE=sync
ALLOW_MISSING=0
for arg in "$@"; do
  case "$arg" in
    --check)         MODE=check ;;
    --allow-missing) ALLOW_MISSING=1 ;;
    -h|--help)       echo "usage: sync.sh [--check] [--allow-missing]"; exit 0 ;;
    *) echo "sync: unknown arg '$arg' (use --check, --allow-missing)" >&2; exit 2 ;;
  esac
done

[[ -f "$BASE" ]] || { echo "sync: missing base-allowlist.txt at $BASE" >&2; exit 1; }
# shellcheck source=paths.sh
source "$HERE/paths.sh"

# Effective (non-comment, non-blank) lines of a file — the host set used by the
# fail-closed host-count safety check in gen_allowlist and the "N hosts" sync message
# (also used to read the vendored-files manifest, which isn't hosts).
domains() { grep -vE '^\s*(#|$)' "$1" 2>/dev/null | sort -u; }

# Minimum sane host count for a generated allowlist. The shared base alone always
# contributes several hosts, so a generated file at/below this floor means the base
# was accidentally emptied or corrupted — which fails every container closed but
# SILENTLY. Refuse to write such a file.
ALLOWLIST_MIN_HOSTS=1

gen_allowlist() {
  local dst="$1" project="$2"
  local extra="$dst/allowlist.extra.txt" out="${3:-$dst/allowlist.txt}"
  local base_hosts outdir tmp n
  base_hosts="$(domains "$BASE")"
  outdir="$(dirname "$out")"
  # Write to a temp in the SAME dir, then atomically mv into place, so an interrupt
  # or disk-full never leaves a truncated allowlist.txt (egress-safe but silently
  # broken until re-sync, with no signal).
  tmp="$(mktemp "$outdir/.allowlist.XXXXXX")" || { echo "sync: ERROR mktemp failed in $outdir" >&2; exit 1; }
  {
    echo "# GENERATED by LockBox/sync.sh v${LOCKBOX_VERSION} — DO NOT EDIT THIS FILE."
    echo "# Effective allowlist = base-allowlist.txt + ${project}/allowlist.extra.txt"
    echo "# Edit the base (LockBox/base-allowlist.txt) or this project's"
    echo "# allowlist.extra.txt, then re-run ./sync.sh and rebuild the container."
    echo
    echo "# ==== shared base ===="
    cat "$BASE"
    echo
    if [[ -f "$extra" ]]; then
      echo "# ==== ${project} project-specific extras ===="
      # Drop extra hosts already in the base: a dup would appear twice in the baked
      # allowlist, inflating the host count shown to a human auditor. Comments/blanks
      # are kept verbatim, and a whitespace-padded dup line is kept (accepted delta).
      # `|| true`: grep exits 1 when every extra line is filtered — must not abort set -e.
      grep -vxF -f <(printf '%s\n' "$base_hosts") -- "$extra" || true
    else
      echo "# (no ${project}/allowlist.extra.txt — base only)"
    fi
  } > "$tmp"
  # Fail-closed: never install an allowlist that lost its hosts (e.g. an emptied base).
  n="$(domains "$tmp" | wc -l | tr -d ' ')"
  if (( n < ALLOWLIST_MIN_HOSTS )); then
    rm -f "$tmp"
    echo "sync: ERROR generated allowlist for '${project}' has ${n} host(s) (< ${ALLOWLIST_MIN_HOSTS}); refusing to write. Is base-allowlist.txt empty?" >&2
    exit 1
  fi
  # mktemp makes the temp 0600; the baked /etc/squid/allowlist.txt is read by squid
  # running as the non-root `proxy` user, so it must be world-readable. Normalize to
  # 0644 (a data file needs no +x either — the old 0755 was spurious).
  chmod 0644 "$tmp"
  mv "$tmp" "$out"
}

# Atomic write: read stdin into a same-dir temp, set mode, mv into place — an
# interrupt or disk-full never leaves a truncated egress file.
write_atomic() {
  local out="$1" mode="$2" tmp
  tmp="$(mktemp "$(dirname "$out")/.tmp.XXXXXX")" || { echo "sync: ERROR mktemp failed for $out" >&2; exit 1; }
  cat > "$tmp"
  chmod "$mode" "$tmp"
  mv "$tmp" "$out"
}

# Write a vendored copy of a canonical file: its EXACT content, then a provenance
# stamp (LockBox version + the canonical file's SHA-256). The stamp lets a baked
# container self-identify its egress-lock generation, and is DETERMINISTIC (version +
# content hash — no timestamp, no commit SHA) so `--check` can regenerate and verify
# it. This is why the vendoring invariant is "vendored == canonical content + this
# exact stamp" (regenerate-and-cmp, like the allowlist) rather than byte-identical.
# Written atomically via write_atomic. $3 = octal mode (default 0644).
gen_vendored() {
  local canonical="$1" out="$2" mode="${3:-0644}"
  local hash
  hash="$(sha256_of "$canonical")"
  {
    cat "$canonical"
    echo
    echo "# ─── vendored by LockBox v${LOCKBOX_VERSION} · canonical sha256:${hash} ───"
    echo "# Generated from the canonical source by LockBox/sync.sh — DO NOT EDIT HERE."
    echo "# Edit LockBox/$(basename "$canonical") and re-run ./sync.sh."
  } | write_atomic "$out" "$mode"
}

# Files vendored (canonical name -> per-project name; same here). Read from the shared
# manifest so a fourth canonical file is added in ONE place — CI's vendored job reads
# the same vendored-files.txt. Each is written as canonical content + a provenance
# stamp (see gen_vendored), NOT byte-identical.
VENDORED=()
while IFS= read -r _vf; do VENDORED+=("$_vf"); done < <(domains "$HERE/vendored-files.txt")
(( ${#VENDORED[@]} > 0 )) || { echo "sync: ERROR no vendored files listed in $HERE/vendored-files.txt" >&2; exit 1; }

# A vendored reference copy is TARGET-INDEPENDENT (canonical content + version +
# canonical SHA-256), so generate each one ONCE up front. Regenerating inside the
# target loop ran gen_vendored — and its sha256_of, a ~40-60ms Perl `shasum` startup
# on macOS — once per file per target in check mode and twice per file per target
# in sync mode (write + verify): 18-36 runs where 3 suffice, paid on EVERY commit
# via the .githooks/pre-commit `--check`. The loops below cmp/cp against these.
REF_DIR="$(mktemp -d)" || { echo "sync: ERROR mktemp -d failed" >&2; exit 1; }
trap 'rm -rf "$REF_DIR"' EXIT
for f in "${VENDORED[@]}"; do
  [[ -f "$HERE/$f" ]] || continue
  gen_vendored "$HERE/$f" "$REF_DIR/$f"
done

synced=0 skipped=0 drift=0 checked=0
for dst in "${EGRESS_DEVCONTAINERS[@]}"; do
  if [[ ! -d "$dst" ]]; then
    echo "SKIP (missing) -> $dst" >&2
    skipped=$((skipped + 1))
    continue
  fi
  project="$(basename "$(dirname "$dst")")"

  if [[ "$MODE" == check ]]; then
    # Verify-only: every vendored copy + the generated allowlist must already
    # match what sync WOULD write; any difference is drift (hand-edit / stale).
    for f in "${VENDORED[@]}"; do
      [[ -f "$REF_DIR/$f" ]] || continue
      if ! cmp -s "$REF_DIR/$f" "$dst/$f"; then
        echo "DRIFT: $dst/$f differs from canonical $f (content or provenance stamp)" >&2; drift=$((drift + 1))
      fi
    done
    tmp="$(mktemp)"; gen_allowlist "$dst" "$project" "$tmp"
    if ! cmp -s "$tmp" "$dst/allowlist.txt"; then
      echo "DRIFT: $dst/allowlist.txt is stale (re-run ./sync.sh)" >&2; drift=$((drift + 1))
    fi
    rm -f "$tmp"
    checked=$((checked + 1))
    continue
  fi

  # Sync: install the pre-generated reference copy atomically (same-dir temp + mv,
  # so an interrupt never leaves a truncated egress file), then VERIFY it landed by
  # cmp'ing the installed file against the reference (a silently short write would
  # otherwise leave a stale/partial egress file in place). init-firewall.sh is
  # executable (it runs as /usr/local/sbin/egress-firewall); the others are 0644.
  for f in "${VENDORED[@]}"; do
    [[ -f "$REF_DIR/$f" ]] || continue
    mode=0644; if [[ "$f" == init-firewall.sh ]]; then mode=0755; fi
    vtmp="$(mktemp "$dst/.vendored.XXXXXX")" || { echo "sync: ERROR mktemp failed in $dst" >&2; exit 1; }
    cp "$REF_DIR/$f" "$vtmp"
    chmod "$mode" "$vtmp"
    mv "$vtmp" "$dst/$f"
    cmp -s "$REF_DIR/$f" "$dst/$f" || { echo "sync: ERROR vendored write verify failed for $dst/$f" >&2; exit 1; }
  done
  gen_allowlist "$dst" "$project"
  echo "synced + generated allowlist ($(domains "$dst/allowlist.txt" | wc -l | tr -d ' ') hosts) -> $dst"
  synced=$((synced + 1))
done

if [[ "$MODE" == check ]]; then
  if (( drift == 0 && skipped == 0 )); then
    echo "✓ check: all $checked vendored copies + allowlists are in sync."
    exit 0
  fi
  echo "✗ check: $drift drift, $skipped missing target(s). Run ./sync.sh." >&2
  exit 1
fi

echo "Done: $synced synced, $skipped skipped. Rebuild affected containers so the baked copies update."
# A missing target means a managed container silently stopped receiving the
# egress lock — fail loudly unless explicitly allowed.
if (( skipped > 0 )) && (( ! ALLOW_MISSING )); then
  echo "sync: ERROR — $skipped target(s) missing (see SKIP above). Fix paths.sh or pass --allow-missing." >&2
  exit 1
fi
