#!/usr/bin/env bash
# Vendoring sync: push the canonical egress files into each devcontainer's
# .devcontainer/, and GENERATE each project's baked allowlist from the shared
# base + that project's overlay.
#
# Edit init-firewall.sh / squid.conf / base-allowlist.txt / launcher-common.sh
# HERE, or a project's .devcontainer/allowlist.extra.txt, then run this and
# rebuild the affected containers. The generated .devcontainer/allowlist.txt is
# NOT hand-edited.
#
# Targets come from paths.sh (shared with audit.sh) — see that file for why.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"
BASE="$HERE/base-allowlist.txt"

# Modes:
#   (default)        copy + generate, then VERIFY each copy with cmp; a missing
#                    target is a HARD failure (this is the bug paths.sh exists to
#                    prevent — a renamed/moved project silently dropping out of
#                    the egress lock). Pass --allow-missing to downgrade to a warn.
#   --check          verify-only: compare every vendored copy + generated allowlist
#                    against what sync WOULD write, and exit non-zero on any drift
#                    (a hand-edited vendored init-firewall.sh/squid.conf/allowlist,
#                    or a missing target). Writes nothing. Good as a pre-commit gate.
MODE=sync
ALLOW_MISSING=0
for arg in "$@"; do
  case "$arg" in
    --check)         MODE=check ;;
    --allow-missing) ALLOW_MISSING=1 ;;
    -h|--help)       echo "usage: sync.sh [--check] [--allow-missing]"; exit 0 ;;
    *) echo "sync: unknown arg '$arg' (use --check, --allow-missing)" >&2; exit 2 ;;
  esac
done

[[ -f "$BASE" ]] || { echo "sync: missing base-allowlist.txt at $BASE" >&2; exit 1; }
# shellcheck source=paths.sh
source "$HERE/paths.sh"

# Effective domain set (non-comment, non-blank) of a file, for the safety check.
domains() { grep -vE '^\s*#' "$1" 2>/dev/null | grep -vE '^\s*$' | sort -u; }

gen_allowlist() {
  local dst="$1" project="$2" extra="$dst/allowlist.extra.txt" out="${3:-$dst/allowlist.txt}"
  {
    echo "# GENERATED by devcontainer-egress/sync.sh — DO NOT EDIT THIS FILE."
    echo "# Effective allowlist = base-allowlist.txt + ${project}/allowlist.extra.txt"
    echo "# Edit the base (devcontainer-egress/base-allowlist.txt) or this project's"
    echo "# allowlist.extra.txt, then re-run ./sync.sh and rebuild the container."
    echo
    echo "# ==== shared base ===="
    cat "$BASE"
    echo
    if [[ -f "$extra" ]]; then
      echo "# ==== ${project} project-specific extras ===="
      cat "$extra"
    else
      echo "# (no ${project}/allowlist.extra.txt — base only)"
    fi
  } > "$out"
}

# Files vendored verbatim (canonical name -> per-project name; same here).
VENDORED=(init-firewall.sh squid.conf launcher-common.sh)

synced=0 skipped=0 drift=0
for dst in "${EGRESS_DEVCONTAINERS[@]}"; do
  if [[ ! -d "$dst" ]]; then
    echo "SKIP (missing) -> $dst" >&2
    skipped=$((skipped + 1))
    continue
  fi
  project="$(basename "$(dirname "$dst")")"

  if [[ "$MODE" == check ]]; then
    # Verify-only: every vendored copy + the generated allowlist must already
    # match what sync WOULD write; any difference is drift (hand-edit / stale).
    for f in "${VENDORED[@]}"; do
      [[ -f "$HERE/$f" ]] || continue
      if ! cmp -s "$HERE/$f" "$dst/$f"; then
        echo "DRIFT: $dst/$f differs from canonical $f" >&2; drift=$((drift + 1))
      fi
    done
    tmp="$(mktemp)"; gen_allowlist "$dst" "$project" "$tmp"
    if ! cmp -s "$tmp" "$dst/allowlist.txt"; then
      echo "DRIFT: $dst/allowlist.txt is stale (re-run ./sync.sh)" >&2; drift=$((drift + 1))
    fi
    rm -f "$tmp"
    synced=$((synced + 1))
    continue
  fi

  # Sync: copy, then VERIFY each copy landed byte-identical (a silently failed cp
  # would otherwise leave a stale/partial egress file in place).
  for f in "${VENDORED[@]}"; do
    [[ -f "$HERE/$f" ]] || continue
    cp "$HERE/$f" "$dst/$f"
    cmp -s "$HERE/$f" "$dst/$f" || { echo "sync: ERROR copy verify failed for $dst/$f" >&2; exit 1; }
  done
  chmod +x "$dst/init-firewall.sh"
  gen_allowlist "$dst" "$project"
  echo "synced + generated allowlist ($(domains "$dst/allowlist.txt" | wc -l | tr -d ' ') hosts) -> $dst"
  synced=$((synced + 1))
done

if [[ "$MODE" == check ]]; then
  if (( drift == 0 && skipped == 0 )); then
    echo "✓ check: all $synced vendored copies + allowlists are in sync."
    exit 0
  fi
  echo "✗ check: $drift drift, $skipped missing target(s). Run ./sync.sh." >&2
  exit 1
fi

echo "Done: $synced synced, $skipped skipped. Rebuild affected containers so the baked copies update."
# A missing target means a managed container silently stopped receiving the
# egress lock — fail loudly unless explicitly allowed.
if (( skipped > 0 )) && (( ! ALLOW_MISSING )); then
  echo "sync: ERROR — $skipped target(s) missing (see SKIP above). Fix paths.sh or pass --allow-missing." >&2
  exit 1
fi
